### ISSUE TITLE
Version Issue

### ISSUE THREAD

**Issue by EMREOYUN** [sgkoishi/Stellaria#3]
It keep says Not Same Version! Both server uses 1.3.0.7(API 2.1) and cannot connectable with eachother.

**Comment by sgkoishi** [comment]
I hardcode the version.
https://github.com/sgkoishi/Stellaria/blob/68209ede15a3a94fed0e10a611a56c0b512a2a9a/Stellaria.cs#L95-L96
You may find the `Main.curRelease` and change the last three numbers if you want.
It's not designed for PE, and might be buggy~~Well it's already buggy~~

**Comment by EMREOYUN** [comment]
> I hardcode the version.
> https://github.com/sgkoishi/Stellaria/blob/68209ede15a3a94fed0e10a611a56c0b512a2a9a/Stellaria.cs#L95-L96
> 
> 
> You may find the `Main.curRelease` and change the last three numbers if you want.
> It's not designed for PE, and might be buggy~Well it's already buggy~

How i can find last 3 numbers for 1.3.0.7

**Comment by sgkoishi** [comment]
> 
> 
> > I hardcode the version.
> > https://github.com/sgkoishi/Stellaria/blob/68209ede15a3a94fed0e10a611a56c0b512a2a9a/Stellaria.cs#L95-L96
> > 
> > You may find the `Main.curRelease` and change the last three numbers if you want.
> > It's not designed for PE, and might be buggy~Well it's already buggy~
> 
> How i can find last 3 numbers for 1.3.0.7

http://ludwig.schafer.free.fr/#curRelease
The `curRelease` of 1.3.0.7 is `155`, or say `49, 53, 53` (0x31, 0x35, 0x35)

**Comment by EMREOYUN** [comment]
> > > I hardcode the version.
> > > https://github.com/sgkoishi/Stellaria/blob/68209ede15a3a94fed0e10a611a56c0b512a2a9a/Stellaria.cs#L95-L96
> > > 
> > > You may find the `Main.curRelease` and change the last three numbers if you want.
> > > It's not designed for PE, and might be buggy~Well it's already buggy~
> > 
> > 
> > How i can find last 3 numbers for 1.3.0.7
> 
> http://ludwig.schafer.free.fr/#curRelease
> The `curRelease` of 1.3.0.7 is `155`, or say `49, 53, 53` (0x31, 0x35, 0x35)

Alright, thank you very much.

**Comment by EMREOYUN** [comment]
It works well but on disconnect, host server crashes with this error):

Unhandled exception
System.UnhandledExceptionEventArgs

2020-03-28 19:52:52 - TShock: ERROR: System.Collections.Generic.KeyNotFoundException: Verilen anahtar sözlükte yoktu.
   konum: System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   konum: Chireiden.Stellaria.Stellaria.ServerLoop(Object state)
   konum: System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   konum: System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   konum: System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   konum: System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   konum: System.Threading.ThreadPoolWorkQueue.Dispatch()
   konum: System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

(I know system is Turkish and does not gives English errors.)
Is it somehow connected with modified code? We disabled various things on PE code for porting to PE well.

**Comment by EMREOYUN** [comment]
@sgkoishi Here is same issue on English:

Unhandled Exception: System.Collections.Generic.KeyNotFoundException: The given
key was not present in the dictionary.
at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
at Chireiden.Stellaria.Stellaria.ServerLoop(Object state)
at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object sta
te)
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionCo
ntext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, C
ontextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWor
kItem.ExecuteWorkItem()
at System.Threading.ThreadPoolWorkQueue.Dispatch()
at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
