### ISSUE TITLE
Wrapper crash on player disconnect

### ISSUE THREAD

**Issue by HotaruBlaze** [sgkoishi/Stellaria#4]
Joining works fine, but whenever a player leaves, the server crashes with the following message
---
```
[ERROR] FATAL UNHANDLED EXCEPTION: System.Collections.Generic.KeyNotFoundException: The given key '0' was not present in the dictionary.
at System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item (TKey key) [0x0001e] in <de0ee687c1ad4ea99fca2db5d4839ca1>:0
at Chireiden.Stellaria.Stellaria.ServerLoop (System.Object state) [0x00187] in <3b2237ba6d1a47eb9bce8a92fc5553bd>:0
at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context (System.Object state) [0x00007] in <de0ee687c1ad4ea99fca2db5d4839ca1>:0
at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00071] in <de0ee687c1ad4ea99fca2db5d4839ca1>:0
at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in <de0ee687c1ad4ea99fca2db5d4839ca1>:0
at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem () [0x00021] in <de0ee687c1ad4ea99fca2db5d4839ca1>:0
at System.Threading.ThreadPoolWorkQueue.Dispatch () [0x00074] in <de0ee687c1ad4ea99fca2db5d4839ca1>:0
at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback () [0x00000] in <de0ee687c1ad4ea99fca2db5d4839ca1>:0
```
---
crash.json 
```json
{
  "os": {
    "x64": "yes",
    "x64Process": "yes",
    "Platform": "Unix",
    "Version": "Unix 5.3.0.40"
  },
  "hardware": {
    "CPUs": 64,
    "CPUID": null
  },
  "server": {
    "Players": 0,
    "MaxPlayers": 255,
    "WorldName": "wrapper",
    "WorldFile": "world.wld",
    "Time": 39281.0
  },
  "process": {
    "curRelease": 194,
    "TSAPIVersion": "1.3.5.3",
    "Uptime": "00:00:36.0343000",
    "WorkingDirectory": "",
    "Arguments": ""
  },
  "memory": [],
  "plugins": [
    {
      "Name": "TShock",
      "Author": "The TShock Team",
      "Version": "4.3.26.0"
    },
    {
      "Name": "Stellaria",
      "Author": "SGKoishi",
      "Version": "1.1.5.0"
    }
  ],
  "exception": {
    "message": "The given key '0' was not present in the dictionary.",
    "type": "KeyNotFoundException",
    "trace": "  at System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item (TKey key) [0x0001e] in <de0ee687c1ad4ea99fca2db5d4839ca1>:0 \n  at Chireiden.Stellaria.Stellaria.ServerLoop (System.Object state) [0x00187] in <3b2237ba6d1a47eb9bce8a92fc5553bd>:0 \n  at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context (System.Object state) [0x00007] in <de0ee687c1ad4ea99fca2db5d4839ca1>:0 \n  at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00071] in <de0ee687c1ad4ea99fca2db5d4839ca1>:0 \n  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in <de0ee687c1ad4ea99fca2db5d4839ca1>:0 \n  at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem () [0x00021] in <de0ee687c1ad4ea99fca2db5d4839ca1>:0 \n  at System.Threading.ThreadPoolWorkQueue.Dispatch () [0x00074] in <de0ee687c1ad4ea99fca2db5d4839ca1>:0 \n  at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback () [0x00000] in <de0ee687c1ad4ea99fca2db5d4839ca1>:0 ",
    "inner": null
  }
}
```

**Comment by sgkoishi** [comment]
You may add a try-catch block for this line:
https://github.com/sgkoishi/Stellaria/blob/68209ede15a3a94fed0e10a611a56c0b512a2a9a/Stellaria.cs#L427

Or checkout [Dimensions](https://github.com/popstarfreas/Dimensions/), `The load-balancing and routing service for Terraria Servers`

**Comment by HotaruBlaze** [comment]
Not had a chance to really look into this, due to players losing their mini-map when changing world, This became unusable for our purpose.

Gonna close the issue, unless other people start having the same issues as before and want to investigate or i return to this project.

**Comment by EMREOYUN** [comment]
@HotaruBlaze reopen it

Unhandled Exception: System.Collections.Generic.KeyNotFoundException: The given
key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Chireiden.Stellaria.Stellaria.ServerLoop(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object sta
te)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionCo
ntext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, C
ontextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWor
kItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
